[tool.poetry]
name = "what-to-eat-bot"
version = "0.1.0"
description = ""
authors = ["duxevy <79513394+duxevy@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
